CREATE TABLE alerta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cidade VARCHAR(120) NOT NULL,
    estado VARCHAR(120),
    pais VARCHAR(80),
    latitude DECIMAL(10, 6) NOT NULL,
    longitude DECIMAL(10, 6) NOT NULL,
    temperatura DECIMAL(5, 2) NOT NULL,
    velocidade_vento DECIMAL(6, 2),
    codigo_clima INT NOT NULL,
    condicao VARCHAR(120) NOT NULL,
    nivel VARCHAR(20) NOT NULL,
    mensagem VARCHAR(255) NOT NULL,
    data_criacao TIMESTAMP NOT NULL,
    data_atualizacao TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);
